version: 0.0
os: linux

files:             
  - source: ./webapp/build/libs/ROOT.war
    destination: /opt/tomcat/webapps

hooks:
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: centos
  ApplicationStart:
   - location: ./applicationStart.sh
     timeout: 180
     runas: centos
  # ValidateService:
  #  - location: ./validateService.sh
  #    timeout: 180
  #    runas: centos